# Generated by Django 3.1 on 2020-08-12 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField(max_length=256)),
                ('image', models.ImageField(upload_to='movies')),
                ('category', models.CharField(choices=[('C', 'Comedy'), ('F', 'Fiction'), ('D', 'Drama'), ('R', 'Romance'), ('A', 'Action')], max_length=1)),
                ('language', models.CharField(choices=[('EN', 'English'), ('ES', 'Espanish'), ('GR', 'German')], max_length=2)),
                ('status', models.CharField(choices=[('MW', 'Most Watched'), ('TR', 'Top Rated'), ('RA', 'Recently Added')], max_length=2)),
                ('year', models.DateField()),
                ('views_count', models.IntegerField(default=0)),
            ],
        ),
    ]
